XCLANG_PATH = /Users/maeikei/workspace/xclang-dev/obj/InstallRoot/bin
CC = $(XCLANG_PATH)/x86_64-pc-linux-gnueabi-xclang
CXX = $(XCLANG_PATH)/x86_64-pc-linux-gnueabi-xclang++
all:
	$(CC) -v main.c -o /tmp/main.c.o
#	$(CXX) -v main.cpp -o /tmp/main.cpp.o
