#include "options.hpp"
using namespace xclang;
#include <boost/assign/list_of.hpp>
using namespace boost::assign;
#include <iostream>
#include <iterator>
using namespace std;


const map<string,int> XClangOptions::m_clang_options = map_list_of
        ("-save-temps",iConstOptionTypeAlone)
        ("-objcmt-migrate-literals",iConstOptionTypeAlone)
        ("--serialize-diagnostics",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-###",iConstOptionTypeAlone)
        ("-ftrap-function",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-emit-ast",iConstOptionTypeAlone)
        ("-Xassembler",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-time",iConstOptionTypeAlone)
        ("-pipe",iConstOptionTypeAlone)
        ("-objcmt-migrate-subscripting",iConstOptionTypeAlone)
        ("-arcmt-migrate-report-output",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-Xpreprocessor",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-Xclang",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("--migrate",iConstOptionTypeAlone)
        ("-working-directory",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-Xanalyzer",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("--analyze",iConstOptionTypeAlone)
        ("-fcatch-undefined-behavior",iConstOptionTypeAlone)
        ("-ObjC++",iConstOptionTypeAlone)
        ("--relocatable-pch",iConstOptionTypeAlone)
        ("-v",iConstOptionTypeAlone)
        ("-target",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-print-prog-name",iConstOptionTypeNextValue| iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-print-libgcc-file-name",iConstOptionTypeAlone)
        ("-o",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-limit-debug-info",iConstOptionTypeAlone)
        ("-c",iConstOptionTypeAlone)
        ("-arcmt-migrate-emit-errors",iConstOptionTypeAlone)
        ("-S",iConstOptionTypeAlone)
        ("-Qunused-arguments",iConstOptionTypeAlone)
        ("-E",iConstOptionTypeAlone)
        ("--help",iConstOptionTypeAlone)
        ("-verify",iConstOptionTypeAlone)
        ("-rewrite-objc",iConstOptionTypeAlone)
        ("-print-file-name",iConstOptionTypeNextValue| iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-Wp",iConstOptionTypeValue| iConstOptionTypeCommaValue | iConstOptionTypeAlone)
        ("-Wl",iConstOptionTypeValue| iConstOptionTypeCommaValue | iConstOptionTypeAlone)
        ("-Wa",iConstOptionTypeValue| iConstOptionTypeCommaValue | iConstOptionTypeAlone)
        ("-print-search-dirs",iConstOptionTypeAlone)
        ("-gcc-toolchain",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-flimit-debug-info",iConstOptionTypeAlone)
        ("-emit-llvm",iConstOptionTypeAlone)
        ("-Xlinker",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ObjC",iConstOptionTypeAlone)
;




const map<string,int> XClangOptions::m_clang_cc1_options  = map_list_of
        ("-working-directory",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-v",iConstOptionTypeAlone)
        ("-nostdinc++",iConstOptionTypeAlone)
        ("-main-file-name",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fshow-column",iConstOptionTypeAlone)
        ("-chain-include",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fblocks-runtime-optional",iConstOptionTypeAlone)
        ("-rewrite-macros",iConstOptionTypeAlone)
        ("-print-preamble",iConstOptionTypeAlone)
        ("-no-code-completion-globals",iConstOptionTypeAlone)
        ("-include-pth",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fobjc-runtime-has-terminate",iConstOptionTypeAlone)
        ("-fdelayed-template-parsing",iConstOptionTypeAlone)
        ("-MG",iConstOptionTypeAlone)
        ("-fno-show-source-location",iConstOptionTypeAlone)
        ("-mstack-alignment",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-iwithprefix",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ast-print",iConstOptionTypeAlone)
        ("-U",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-cl-single-precision-constant",iConstOptionTypeAlone)
        ("-objcmt-migrate-subscripting",iConstOptionTypeAlone)
        ("-CC",iConstOptionTypeAlone)
        ("-fix-only-warnings",iConstOptionTypeAlone)
        ("-fno-constant-cfstrings",iConstOptionTypeAlone)
        ("-analyzer-max-loop",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-diagnostics-show-note-include-stack",iConstOptionTypeAlone)
        ("-fdiagnostics-format",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-Wno-rewrite-macros",iConstOptionTypeAlone)
        ("-fshort-enums",iConstOptionTypeAlone)
        ("-Os",iConstOptionTypeAlone)
        ("-w",iConstOptionTypeAlone)
        ("-token-cache",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-sys-header-deps",iConstOptionTypeAlone)
        ("-c-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdebugger-objc-literal",iConstOptionTypeAlone)
        ("-fmodule-name",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-preamble-bytes",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-mt-migrate-directory",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-mstackrealign",iConstOptionTypeAlone)
        ("-analyzer-store",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ftabstop",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-msave-temp-labels",iConstOptionTypeAlone)
        ("-fcxx-exceptions",iConstOptionTypeAlone)
        ("-cfg-add-initializers",iConstOptionTypeAlone)
        ("-serialize-diagnostic-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-objc-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-index-header-map",iConstOptionTypeAlone)
        ("-ffreestanding",iConstOptionTypeAlone)
        ("-fno-common",iConstOptionTypeAlone)
        ("-fno-inline",iConstOptionTypeAlone)
        ("-fno-const-strings",iConstOptionTypeAlone)
        ("-fno-dollars-in-identifiers",iConstOptionTypeAlone)
        ("-fno-diagnostics-fixit-info",iConstOptionTypeAlone)
        ("-cxx-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdebugger-cast-result-to-id",iConstOptionTypeAlone)
        ("-MT",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-dM",iConstOptionTypeAlone)
        ("-fixit-to-temporary",iConstOptionTypeAlone)
        ("-ast-view",iConstOptionTypeAlone)
        ("-mms-bitfields",iConstOptionTypeAlone)
        ("-internal-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fwrapv",iConstOptionTypeAlone)
        ("-analyzer-ipa",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fforbid-guard-variables",iConstOptionTypeAlone)
        ("-analyzer-constraints",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-coverage-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-no-ns-alloc-error",iConstOptionTypeAlone)
        ("-iwithprefixbefore",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-disable-free",iConstOptionTypeAlone)
        ("-pg",iConstOptionTypeAlone)
        ("-ftrap-function",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-pthread",iConstOptionTypeAlone)
        ("-munwind-tables",iConstOptionTypeAlone)
        ("-header-include-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdollars-in-identifiers",iConstOptionTypeAlone)
        ("-arcmt-migrate-emit-errors",iConstOptionTypeAlone)
        ("-fcuda-is-device",iConstOptionTypeAlone)
        ("-version",iConstOptionTypeAlone)
        ("-mrelax-all",iConstOptionTypeAlone)
        ("-fno-inline-functions",iConstOptionTypeAlone)
        ("-fapple-pragma-pack",iConstOptionTypeAlone)
        ("-fobjc-gc-only",iConstOptionTypeAlone)
        ("-fgnu89-inline",iConstOptionTypeAlone)
        ("-fmessage-length",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdump-record-layouts",iConstOptionTypeAlone)
        ("-ast-dump-xml",iConstOptionTypeAlone)
        ("-fdiagnostics-parseable-fixits",iConstOptionTypeAlone)
        ("-plugin-arg",iConstOptionTypeNextValue| iConstOptionTypeValue| iConstOptionTypeBarValue | iConstOptionTypeAlone)
        ("-mno-global-merge",iConstOptionTypeAlone)
        ("-mdisable-tail-calls",iConstOptionTypeAlone)
        ("-fgnu-keywords",iConstOptionTypeAlone)
        ("-unoptimized-cfg",iConstOptionTypeAlone)
        ("-mlimit-float-precision",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ffunction-sections",iConstOptionTypeAlone)
        ("-cfg-add-implicit-dtors",iConstOptionTypeAlone)
        ("-fuse-register-sized-bitfield-access",iConstOptionTypeAlone)
        ("-pubnames-dump",iConstOptionTypeAlone)
        ("-mregparm",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-mqdsp6-compat",iConstOptionTypeAlone)
        ("-fmodules",iConstOptionTypeAlone)
        ("-Eonly",iConstOptionTypeAlone)
        ("-ftrapv-handler",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-analyzer-opt-analyze-nested-blocks",iConstOptionTypeAlone)
        ("-stdlib",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-print-decl-contexts",iConstOptionTypeAlone)
        ("-analyzer-output",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdebug-compilation-dir",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-cl-fast-relaxed-math",iConstOptionTypeAlone)
        ("-fdump-record-layouts-simple",iConstOptionTypeAlone)
        ("-static-define",iConstOptionTypeAlone)
        ("-no-implicit-float",iConstOptionTypeAlone)
        ("-mrelocation-model",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-backend-option",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-merge-all-constants",iConstOptionTypeAlone)
        ("-print-stats",iConstOptionTypeAlone)
        ("-print-ivar-layout",iConstOptionTypeAlone)
        ("-o",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdiagnostics-show-note-include-stack",iConstOptionTypeAlone)
        ("-dD",iConstOptionTypeAlone)
        ("-analyzer-max-nodes",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-signed-char",iConstOptionTypeAlone)
        ("-add-plugin",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-trigraphs",iConstOptionTypeAlone)
        ("-pic-level",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-mdebug-pass",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-iframework",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-emit-html",iConstOptionTypeAlone)
        ("-ffast-math",iConstOptionTypeAlone)
        ("-relaxed-aliasing",iConstOptionTypeAlone)
        ("-nostdsysteminc",iConstOptionTypeAlone)
        ("-mfloat-abi",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-arcmt-migrate",iConstOptionTypeAlone)
        ("-dump-raw-tokens",iConstOptionTypeAlone)
        ("-arcmt-check",iConstOptionTypeAlone)
        ("-C",iConstOptionTypeAlone)
        ("-dump-tokens",iConstOptionTypeAlone)
        ("-analyzer-inlining-mode",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-femit-coverage-notes",iConstOptionTypeAlone)
        ("-menable-unsafe-fp-math",iConstOptionTypeAlone)
        ("-fno-limit-debug-info",iConstOptionTypeAlone)
        ("-fobjc-arc",iConstOptionTypeAlone)
        ("-fdisable-module-hash",iConstOptionTypeAlone)
        ("-detailed-preprocessing-record",iConstOptionTypeAlone)
        ("-fno-builtin",iConstOptionTypeAlone)
        ("-menable-no-infs",iConstOptionTypeAlone)
        ("-fvisibility-inlines-hidden",iConstOptionTypeAlone)
        ("-fno-rtti",iConstOptionTypeAlone)
        ("-fconstant-string-class",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-init-only",iConstOptionTypeAlone)
        ("-include-pch",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-operator-names",iConstOptionTypeAlone)
        ("-imacros",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-O",iConstOptionTypeValue| iConstOptionTypeAlone)
        ("-cl-opt-disable",iConstOptionTypeAlone)
        ("-emit-codegen-only",iConstOptionTypeAlone)
        ("-fobjc-default-synthesize-properties",iConstOptionTypeAlone)
        ("-fno-spell-checking",iConstOptionTypeAlone)
        ("-D",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fpascal-strings",iConstOptionTypeAlone)
        ("-fapple-kext",iConstOptionTypeAlone)
        ("-code-completion-macros",iConstOptionTypeAlone)
        ("-analyzer-eagerly-assume",iConstOptionTypeAlone)
        ("-analyzer-no-eagerly-trim-egraph",iConstOptionTypeAlone)
        ("-faltivec",iConstOptionTypeAlone)
        ("-stack-protector",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-emit-pth",iConstOptionTypeAlone)
        ("-fobjc-exceptions",iConstOptionTypeAlone)
        ("-fno-validate-pch",iConstOptionTypeAlone)
        ("-disable-llvm-verifier",iConstOptionTypeAlone)
        ("-funknown-anytype",iConstOptionTypeAlone)
        ("-objcmt-migrate-literals",iConstOptionTypeAlone)
        ("-fvisibility",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fmacro-backtrace-limit",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-use-cxa-atexit",iConstOptionTypeAlone)
        ("-fobjc-dispatch-method",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-mdisable-fp-elim",iConstOptionTypeAlone)
        ("-ftemplate-depth",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-emit-module",iConstOptionTypeAlone)
        ("-cl-mad-enable",iConstOptionTypeAlone)
        ("-fhidden-weak-vtables",iConstOptionTypeAlone)
        ("-mno-zero-initialized-in-bss",iConstOptionTypeAlone)
        ("-analyzer-viz-egraph-ubigraph",iConstOptionTypeAlone)
        ("-code-completion-patterns",iConstOptionTypeAlone)
        ("-P",iConstOptionTypeAlone)
        ("-flimit-debug-info",iConstOptionTypeAlone)
        ("-target-abi",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-load",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ferror-limit",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fms-extensions",iConstOptionTypeAlone)
        ("-E",iConstOptionTypeAlone)
        ("-fobjc-arc-cxxlib",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-fdiagnostics-show-category",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-trim-egraph",iConstOptionTypeAlone)
        ("-analyze-function",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-analyzer-inline-max-function-size",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fobjc-runtime-has-weak",iConstOptionTypeAlone)
        ("-fix-what-you-can",iConstOptionTypeAlone)
        ("-mnoexecstack",iConstOptionTypeAlone)
        ("-mcode-model",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-g",iConstOptionTypeAlone)
        ("-dump-build-information",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fsjlj-exceptions",iConstOptionTypeAlone)
        ("-femit-coverage-data",iConstOptionTypeAlone)
        ("-fno-elide-constructors",iConstOptionTypeAlone)
        ("-fdebugger-support",iConstOptionTypeAlone)
        ("-fno-gnu-keywords",iConstOptionTypeAlone)
        ("-target-feature",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-internal-externc-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-objc-infer-related-result-type",iConstOptionTypeAlone)
        ("-fexceptions",iConstOptionTypeAlone)
        ("-ast-merge",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ftemplate-backtrace-limit",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-iquote",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fconst-strings",iConstOptionTypeAlone)
        ("-dependency-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-analyzer-purge",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ffake-address-space-map",iConstOptionTypeAlone)
        ("-migrate",iConstOptionTypeAlone)
        ("-fobjc-arc-exceptions",iConstOptionTypeAlone)
        ("-fborland-extensions",iConstOptionTypeAlone)
        ("-F",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fgnu-runtime",iConstOptionTypeAlone)
        ("-analyzer-opt-analyze-headers",iConstOptionTypeAlone)
        ("-diagnostic-log-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-Oz",iConstOptionTypeAlone)
        ("-fno-access-control",iConstOptionTypeAlone)
        ("-std",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-objcxx-isystem",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-masm-verbose",iConstOptionTypeAlone)
        ("-ast-dump",iConstOptionTypeAlone)
        ("-fno-assume-sane-operator-new",iConstOptionTypeAlone)
        ("-fcatch-undefined-behavior",iConstOptionTypeAlone)
        ("-fno-threadsafe-statics",iConstOptionTypeAlone)
        ("-fobjc-gc",iConstOptionTypeAlone)
        ("-analyze",iConstOptionTypeAlone)
        ("-remap-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-msoft-float",iConstOptionTypeAlone)
        ("-fconstexpr-depth",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-analyzer-disable-checker",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-menable-no-nans",iConstOptionTypeAlone)
        ("-idirafter",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-foverride-record-layout",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-fobjc-runtime-has-arc",iConstOptionTypeAlone)
        ("-fpack-struct",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdiagnostics-print-source-range-info",iConstOptionTypeAlone)
        ("-rewrite-test",iConstOptionTypeAlone)
        ("-mrtd",iConstOptionTypeAlone)
        ("-help",iConstOptionTypeAlone)
        ("-fmodule-cache-path",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-show-column",iConstOptionTypeAlone)
        ("-fno-bitfield-type-align",iConstOptionTypeAlone)
        ("-fno-lax-vector-conversions",iConstOptionTypeAlone)
        ("-finstrument-functions",iConstOptionTypeAlone)
        ("-momit-leaf-frame-pointer",iConstOptionTypeAlone)
        ("-mconstructor-aliases",iConstOptionTypeAlone)
        ("-fwritable-strings",iConstOptionTypeAlone)
        ("-fsyntax-only",iConstOptionTypeAlone)
        ("-arcmt-migrate-report-output",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-analyzer-viz-egraph-graphviz",iConstOptionTypeAlone)
        ("-code-completion-at",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-faddress-sanitizer",iConstOptionTypeAlone)
        ("-analyzer-checker-help",iConstOptionTypeAlone)
        ("-cl-unsafe-math-optimizations",iConstOptionTypeAlone)
        ("-ftime-report",iConstOptionTypeAlone)
        ("-emit-pch",iConstOptionTypeAlone)
        ("-fdata-sections",iConstOptionTypeAlone)
        ("-undef",iConstOptionTypeAlone)
        ("-emit-llvm-bc",iConstOptionTypeAlone)
        ("-cl-finite-math-only",iConstOptionTypeAlone)
        ("-fmath-errno",iConstOptionTypeAlone)
        ("-MP",iConstOptionTypeAlone)
        ("-triple",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-rewrite-objc",iConstOptionTypeAlone)
        ("-fixit",iConstOptionTypeAlone)
        ("-analyzer-stats",iConstOptionTypeAlone)
        ("-emit-llvm",iConstOptionTypeAlone)
        ("-cxx-abi",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fno-deprecated-macro",iConstOptionTypeAlone)
        ("-mlink-bitcode-file",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-femit-all-decls",iConstOptionTypeAlone)
        ("-fshow-overloads",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-disable-llvm-optzns",iConstOptionTypeAlone)
        ("-fno-dwarf-directory-asm",iConstOptionTypeAlone)
        ("-fms-compatibility",iConstOptionTypeAlone)
        ("-fmsc-version",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-resource-dir",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-nobuiltininc",iConstOptionTypeAlone)
        ("-S",iConstOptionTypeAlone)
        ("-fno-dwarf2-cfi-asm",iConstOptionTypeAlone)
        ("-cl-std",iConstOptionTypeValue| iConstOptionTypeEQValue | iConstOptionTypeAlone)
        ("-relocatable-pch",iConstOptionTypeAlone)
        ("-H",iConstOptionTypeAlone)
        ("-analyzer-display-progress",iConstOptionTypeAlone)
        ("-dependency-dot",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-iwithsysroot",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-iprefix",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fixit-recompile",iConstOptionTypeAlone)
        ("-emit-llvm-only",iConstOptionTypeAlone)
        ("-analyzer-inline-max-stack-depth",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-error-on-deserialized-decl",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fshort-wchar",iConstOptionTypeAlone)
        ("-traditional-cpp",iConstOptionTypeAlone)
        ("-no-finalize-removal",iConstOptionTypeAlone)
        ("-mllvm",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-analyzer-checker",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-MQ",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-disable-red-zone",iConstOptionTypeAlone)
        ("-include",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-fdump-vtable-layouts",iConstOptionTypeAlone)
        ("-fconstexpr-backtrace-limit",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-dwarf-debug-flags",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-arcmt-modify",iConstOptionTypeAlone)
        ("-target-linker-version",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-isysroot",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-dump-deserialized-decls",iConstOptionTypeAlone)
        ("-fcolor-diagnostics",iConstOptionTypeAlone)
        ("-emit-obj",iConstOptionTypeAlone)
        ("-verify",iConstOptionTypeAlone)
        ("-plugin",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-I",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-funroll-loops",iConstOptionTypeAlone)
        ("-fdeprecated-macro",iConstOptionTypeAlone)
        ("-fobjc-fragile-abi",iConstOptionTypeAlone)
        ("-target-cpu",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-Wlarge-by-value-copy",iConstOptionTypeNextValue| iConstOptionTypeAlone)
        ("-ftrapv",iConstOptionTypeAlone)
        ("-fno-caret-diagnostics",iConstOptionTypeAlone)
        ("-fblocks",iConstOptionTypeAlone)
        ("-fdiagnostics-show-option",iConstOptionTypeAlone)
;
